#!/bin/bash

fileDirectory="/home/$USER/.config/repos"
configDirectory="/home/$USER/.config"

PATH="$fileDirectory/utils/bin:$PATH"

# setup .xinitrc file first

cd
sudo ln -s $fileDirectory/utils/.xinitrc /home/$USER/.xinitrc
# add error handling for cases where files like .xinitr are not there

# setting up tmux
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# -------- SETTING UP SYMBOLIC LINKS -----------

# setup system fonts and theme
cd /home/$USER/.config
linkRepos=(
    "tmux"
    "wal"
    "yt-dlp"
    "newsboat"
    "mpv"
    "gtk-3.0"
    "dunst"
)

for directory in "${linkRepos[@]}"
do
    # need to add that if no such file is there, only then do this
    sudo ln -s $fileDirectory/utils/$directory $configDirectory/$directory
done

sudo ln -s $fileDirectory/nvim $configDirectory/nvim


# system fonts
sudo ln -s $fileDirectory/utils/fonts /usr/share/fonts/fonts
fc-cache

[ -d "/home/$USER/.cache/wal" ] && true || mkdir /home/$USER/.cache/wal
cp -r $fileDirectory/utils/wal/wal.example/* /home/$USER/.cache/wal

# changing the default shell bash -> zsh 
ln -s $fileDirectory/utils/zsh/.zshrc /home/$USER/.zshrc
ln -s $fileDirectory/utils/zsh/.zprofile /home/$USER/.zprofile

sudo echo "/usr/bin/zsh" >> /etc/shells

sudo chsh -s $(which zsh)
chsh -s $(which zsh)

# I have to check why dmenu is not building
#   Turns out that There was a commit, which 
#   wasn't pushed ;)

buildsuckless
[ -d "/home/$USER/archives/yt-dlp" ] && true || mkdir -p "/home/$USER/archives/yt-dlp"
reboot







