#!/bin/bash


directory="/home/$USER/.config/repos"

[ -d $configDIR ] && true || mkdir -p $configDIR
cd ~/.config/repos


# sahil
repos=(
    # "gautamsahil1947"
    # "studies" 
    "utils"
    "nvim"
    # "install"
    # "cpp"

    # suckless
    "dwm"
    "st"
    "dmenu"
    
)

github="gautamsahil1947"
for repo in "${repos[@]}"
do
    [ -d "$directory/$repo" ] && true || git clone https://github.com/$github/$repo
done

# put the fonts in the right place
# sudo cp -r "$directory/utils/fonts" /usr/share/fonts
