#!/bin/bash
# Add option to remove them all if exist, and install via ssh
# as during fresh installation, these are cloned using https

# this should be implemented using maybe the first argument ($1)
# or something else


directory="/home/$USER/.config/repos"

# check if directory is there or not
# also [ has a return value ] there fore 1>/dev/null 2>&1 maybe
[ -d $directory ] && true || mkdir -p ~/.config/repos
cd ~/.config/repos


repos=(
    # "gautamsahil1947"
    # "studies" 
    "utils"
    "nvim"
    # "install"
    # "cpp"

    # suckless
    "dwm"
    "st"
    "dmenu"
    
)

github="gautamsahil1947"
for repo in "${repos[@]}"
do
    [ -d "$directory/$repo" ] && true || git clone https://github.com/$github/$repo
done

# put the fonts in the right place
# sudo cp -r "$directory/utils/fonts" /usr/share/fonts
